name: Sync to Target Repository

on:
  push:
    branches:
      - master  # 监听 main 分支的推送，可以改成你需要的分支

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0  # 获取完整历史记录

      - name: Push to target repo
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          # 2. 添加远程仓库，注意这里将 Token 嵌入到了 URL 中
            # 格式是：https://用户名:Token@仓库地址
            git remote add target https://yxtcfw:${{ secrets.DEPLOY_TOKEN }}@github.com/yxtcfw/yxtcfw.github.io.git
    
            # 3. 强制推送到目标仓库
            git push target master --force